---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
platforms:
  - name: vagrant-win${WIN_VERSION:-2012R2}
    box: jborean93/WindowsServer${WIN_VERSION:-2012R2}
    memory: 2048
provisioner:
  name: ansible
  inventory:
    host_vars:
      vagrant-win${WIN_VERSION:-2012R2}:
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_port: 55986
        ansible_host: 127.0.0.1
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
        ansible_winrm_scheme: https
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 200
        ansible_winrm_read_timeout_sec: 300
verifier:
  name: ansible
